# Generated by Django 3.2.8 on 2021-11-27 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('actual_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200, null=True)),
                ('academic', models.CharField(blank=True, max_length=200, null=True)),
                ('percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('english', models.CharField(blank=True, max_length=30, null=True)),
                ('intake', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Phd', 'Phd')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('File Submitted', 'File Submitted'), ('Conditional Offer', 'Conditional Offer'), ('Unconditional Offer', 'Unconditional Offer'), ('Offer rejected', 'Offer rejected'), ('Deposit Paid', 'Deposit Paid'), ('Interview', 'Interview'), ('CAS Requested', 'CAS Requested'), ('CAS Issued', 'CAS Issued'), ('VFS Appointment', 'VFS Appointment'), ('Visa Granted', 'Visa Granted'), ('Visa Rejected', 'Visa Rejected')], max_length=50, null=True)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.CharField(blank=True, max_length=500, null=True)),
                ('passport', models.FileField(blank=True, null=True, upload_to='documents')),
                ('academic_transcript', models.FileField(blank=True, null=True, upload_to='documents')),
                ('ielts', models.FileField(blank=True, null=True, upload_to='documents')),
                ('sop', models.FileField(blank=True, null=True, upload_to='documents')),
                ('cv', models.FileField(blank=True, null=True, upload_to='documents')),
                ('reference', models.FileField(blank=True, null=True, upload_to='documents')),
                ('work_experience', models.FileField(blank=True, null=True, upload_to='documents')),
                ('visa', models.FileField(blank=True, null=True, upload_to='documents')),
                ('application_screenshot', models.FileField(blank=True, null=True, upload_to='documents')),
                ('other', models.FileField(blank=True, null=True, upload_to='documents')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='documents')),
                ('application_form', models.FileField(blank=True, null=True, upload_to='documents')),
                ('citizenship', models.FileField(blank=True, null=True, upload_to='documents')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
