# Generated by Django 3.2.8 on 2021-11-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20211117_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('phd', 'Phd')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('file_submitted', 'File Submitted'), ('conditional_offer', 'Conditional Offer'), ('unconditional_offer', 'Unconditional Offer'), ('offer_rejected', 'Offer rejected'), ('deposit_paid', 'Deposit Paid'), ('interview', 'Interview'), ('cas_requested', 'CAS Requested'), ('cas_issued', 'CAS Issued'), ('vfs_appointment', 'VFS Appointment'), ('visa_granted', 'Visa Granted'), ('visa_rejected', 'Visa Rejected')], max_length=50, null=True),
        ),
    ]
