# Generated by Django 3.2.8 on 2021-11-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20211120_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='actual_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='english',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate'), ('Phd', 'Phd')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, choices=[('File Submitted', 'File Submitted'), ('Conditional Offer', 'Conditional Offer'), ('Unconditional Offer', 'Unconditional Offer'), ('Offer rejected', 'Offer rejected'), ('Deposit Paid', 'Deposit Paid'), ('Interview', 'Interview'), ('CAS Requested', 'CAS Requested'), ('CAS Issued', 'CAS Issued'), ('VFS Appointment', 'VFS Appointment'), ('Visa Granted', 'Visa Granted'), ('Visa Rejected', 'Visa Rejected')], max_length=50, null=True),
        ),
    ]
